version: "3.9"
services:
  db:
    image: postgres:15.4
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}

  web:
    build: .
    volumes:
      - .:/app
    restart: always
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    depends_on:
      - db

volumes:
  pg_data: {}
